-- WebScout
-- V1__initial_schema.sql
-- PostgreSQL + Flyway
--
-- Locked V1 conventions:
--   * BIGINT IDENTITY primary keys
--   * TIMESTAMPTZ for persisted instants
--   * Asia/Kolkata (+05:30) is the application/API presentation convention
--   * Flyway owns schema evolution
--   * Hibernate/JPA uses ddl-auto=validate
--
-- This migration intentionally creates the schema in dependency order.
-- Do not use PostgreSQL ENUM types for V1 status fields; VARCHAR + CHECK
-- constraints keep schema evolution explicit.

-- ============================================================
-- 1. users
-- ============================================================

CREATE TABLE users (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email           VARCHAR(320) NOT NULL,
                       password_hash   VARCHAR(255) NOT NULL,
                       status          VARCHAR(20) NOT NULL,
                       created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uq_users_email
                           UNIQUE (email),

                       CONSTRAINT chk_users_status
                           CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- ============================================================
-- 2. sources
-- ============================================================

CREATE TABLE sources (
                         id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id               BIGINT NOT NULL,
                         name                  VARCHAR(255) NOT NULL,
                         base_url              VARCHAR(2048) NOT NULL,
                         enabled               BOOLEAN NOT NULL DEFAULT TRUE,
                         crawl_delay_seconds   INTEGER NOT NULL,
                         request_timeout_ms    INTEGER NOT NULL,
                         max_pages             INTEGER NOT NULL,
                         allowed_path_prefix   VARCHAR(2048),
                         user_agent            VARCHAR(512) NOT NULL,
                         created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_sources_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id)
                                 ON DELETE RESTRICT,

                         CONSTRAINT uq_sources_user_name
                             UNIQUE (user_id, name),

                         CONSTRAINT chk_sources_crawl_delay
                             CHECK (crawl_delay_seconds >= 0),

                         CONSTRAINT chk_sources_request_timeout
                             CHECK (request_timeout_ms > 0),

                         CONSTRAINT chk_sources_max_pages
                             CHECK (max_pages > 0)
);

CREATE INDEX idx_sources_user_enabled
    ON sources (user_id, enabled);

-- ============================================================
-- 3. topics
-- ============================================================

CREATE TABLE topics (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id         BIGINT NOT NULL,
                        name            VARCHAR(255) NOT NULL,
                        description     TEXT,
                        enabled         BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_topics_user
                            FOREIGN KEY (user_id)
                                REFERENCES users(id)
                                ON DELETE RESTRICT,

                        CONSTRAINT uq_topics_user_name
                            UNIQUE (user_id, name)
);

-- ============================================================
-- 4. topic_keywords
-- ============================================================

CREATE TABLE topic_keywords (
                                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                topic_id            BIGINT NOT NULL,
                                keyword             VARCHAR(255) NOT NULL,
                                normalized_keyword  VARCHAR(255) NOT NULL,
                                weight              INTEGER NOT NULL,
                                excluded            BOOLEAN NOT NULL DEFAULT FALSE,

                                CONSTRAINT fk_topic_keywords_topic
                                    FOREIGN KEY (topic_id)
                                        REFERENCES topics(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT uq_topic_keywords_topic_normalized
                                    UNIQUE (topic_id, normalized_keyword),

                                CONSTRAINT chk_topic_keywords_weight
                                    CHECK (weight > 0)
);

-- ============================================================
-- 5. crawl_jobs
-- ============================================================

CREATE TABLE crawl_jobs (
                            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            source_id           BIGINT NOT NULL,
                            retry_of_job_id     BIGINT,
                            status              VARCHAR(20) NOT NULL,
                            trigger_type        VARCHAR(20) NOT NULL,
                            started_at          TIMESTAMPTZ,
                            finished_at         TIMESTAMPTZ,
                            pages_discovered    INTEGER NOT NULL DEFAULT 0,
                            pages_processed     INTEGER NOT NULL DEFAULT 0,
                            pages_succeeded     INTEGER NOT NULL DEFAULT 0,
                            pages_skipped       INTEGER NOT NULL DEFAULT 0,
                            pages_failed        INTEGER NOT NULL DEFAULT 0,
                            error_code          VARCHAR(100),
                            error_message       TEXT,
                            created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_crawl_jobs_source
                                FOREIGN KEY (source_id)
                                    REFERENCES sources(id)
                                    ON DELETE RESTRICT,

                            CONSTRAINT fk_crawl_jobs_retry_of
                                FOREIGN KEY (retry_of_job_id)
                                    REFERENCES crawl_jobs(id)
                                    ON DELETE RESTRICT,

                            CONSTRAINT chk_crawl_jobs_status
                                CHECK (status IN (
                                                  'QUEUED',
                                                  'RUNNING',
                                                  'COMPLETED',
                                                  'FAILED',
                                                  'CANCELLED'
                                    )),

                            CONSTRAINT chk_crawl_jobs_trigger_type
                                CHECK (trigger_type IN (
                                                        'MANUAL',
                                                        'SCHEDULED'
                                    )),

                            CONSTRAINT chk_crawl_jobs_pages_discovered
                                CHECK (pages_discovered >= 0),

                            CONSTRAINT chk_crawl_jobs_pages_processed
                                CHECK (pages_processed >= 0),

                            CONSTRAINT chk_crawl_jobs_pages_succeeded
                                CHECK (pages_succeeded >= 0),

                            CONSTRAINT chk_crawl_jobs_pages_skipped
                                CHECK (pages_skipped >= 0),

                            CONSTRAINT chk_crawl_jobs_pages_failed
                                CHECK (pages_failed >= 0)
);

CREATE INDEX idx_crawl_jobs_source_status
    ON crawl_jobs (source_id, status);

CREATE INDEX idx_crawl_jobs_source_created_at
    ON crawl_jobs (source_id, created_at DESC);

CREATE INDEX idx_crawl_jobs_retry_of
    ON crawl_jobs (retry_of_job_id);

-- ============================================================
-- 6. web_pages
-- ============================================================

CREATE TABLE web_pages (
                           id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           source_id            BIGINT NOT NULL,
                           original_url         VARCHAR(2048) NOT NULL,
                           canonical_url        VARCHAR(2048),
                           normalized_url       VARCHAR(2048) NOT NULL,
                           url_hash             VARCHAR(64) NOT NULL,
                           title                VARCHAR(1000),
                           description          TEXT,
                           content              TEXT NOT NULL,
                           content_hash         VARCHAR(64) NOT NULL,
                           published_at         TIMESTAMPTZ,
                           first_discovered_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           last_crawled_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           last_changed_at      TIMESTAMPTZ,
                           http_status          INTEGER,
                           content_type         VARCHAR(255),

                           CONSTRAINT fk_web_pages_source
                               FOREIGN KEY (source_id)
                                   REFERENCES sources(id)
                                   ON DELETE RESTRICT,

                           CONSTRAINT uq_web_pages_source_url_hash
                               UNIQUE (source_id, url_hash)
);

CREATE INDEX idx_web_pages_source_last_crawled
    ON web_pages (source_id, last_crawled_at DESC);

CREATE INDEX idx_web_pages_published_at
    ON web_pages (published_at);

-- ============================================================
-- 7. crawl_page_results
-- ============================================================

CREATE TABLE crawl_page_results (
                                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    crawl_job_id    BIGINT NOT NULL,
                                    page_id         BIGINT,
                                    url             VARCHAR(2048) NOT NULL,
                                    status          VARCHAR(20) NOT NULL,
                                    http_status     INTEGER,
                                    duration_ms     BIGINT NOT NULL,
                                    error_code      VARCHAR(100),
                                    error_message   TEXT,
                                    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CONSTRAINT fk_crawl_page_results_job
                                        FOREIGN KEY (crawl_job_id)
                                            REFERENCES crawl_jobs(id)
                                            ON DELETE CASCADE,

                                    CONSTRAINT fk_crawl_page_results_page
                                        FOREIGN KEY (page_id)
                                            REFERENCES web_pages(id)
                                            ON DELETE RESTRICT,

                                    CONSTRAINT chk_crawl_page_results_status
                                        CHECK (status IN (
                                                          'SUCCESS',
                                                          'UNCHANGED',
                                                          'CHANGED',
                                                          'SKIPPED',
                                                          'FAILED'
                                            )),

                                    CONSTRAINT chk_crawl_page_results_duration
                                        CHECK (duration_ms >= 0)
);

CREATE INDEX idx_crawl_page_results_job
    ON crawl_page_results (crawl_job_id);

CREATE INDEX idx_crawl_page_results_page_created
    ON crawl_page_results (page_id, created_at DESC);

-- ============================================================
-- 8. audit_logs
-- ============================================================

CREATE TABLE audit_logs (
                            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id       BIGINT,
                            action        VARCHAR(100) NOT NULL,
                            entity_type   VARCHAR(100) NOT NULL,
                            entity_id     BIGINT,
                            metadata      JSONB,
                            occurred_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            request_id    VARCHAR(100),

                            CONSTRAINT fk_audit_logs_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
                                    ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_user_occurred
    ON audit_logs (user_id, occurred_at DESC);

-- ============================================================
-- Migration notes
-- ============================================================
--
-- 1. URL syntax, HTTP/HTTPS enforcement, URL normalization,
--    crawl scope and SSRF protection are application-layer rules.
--
-- 2. Source crawl_delay_seconds, request_timeout_ms and max_pages
--    have positive/non-negative database invariants here. Their
--    operational upper bounds belong to application configuration.
--
-- 3. Timestamps are stored as TIMESTAMPTZ. The application/API
--    convention is Asia/Kolkata; the migration does not issue a
--    global SET TIME ZONE because session timezone is an application
--    concern and TIMESTAMPTZ represents an absolute instant.
--
-- 4. There is deliberately no broad ON DELETE CASCADE from users,
--    sources or topics. Historical crawl/page data is protected.
--
-- 5. topic -> topic_keywords and crawl_job -> crawl_page_results
--    are the intentional V1 cascading relationships.
--
-- 6. audit_logs.user_id becomes NULL if the user is deleted so the
--    audit record itself can survive.
--
-- 7. Page identity is source_id + normalized URL identity, with
--    url_hash used as the compact deterministic uniqueness key.
--
-- 8. A retry is represented by a new crawl_jobs row. retry_of_job_id
--    preserves lineage and does not mutate the terminal historical job.
