package com.webscout.exception;

public enum ErrorCode {

    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_REUSE_DETECTED,
    VALIDATION_ERROR,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR
}