spring:
  application:
    name: webscout

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  spring:
    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-lifetime: 15m

logging:
  level:
    root: INFO
    com.webscout: DEBUG